### PR TITLE
Environments/toricgame

### PR DESCRIPTION
**Pull request by everthemore**
Adding the "Toric Game" environment from https://arxiv.org/abs/2101.08093.
Has overlap with the SurfaceCode decoding environment, but:

- is a leaner version 
- does toric (periodic boundaries) only
- implements "perspectives"

### CODE REVIEW

**Comment by everthemore** [comment]
This environment is adapted from [https://github.com/condensedAI/neat-qec](https://github.com/condensedAI/neat-qec), and is untested in its current form (anyone?).

That corresponding repository will be made public soon!

**Comment by HendrikPN** [comment]
Thanks for the PR. I have finally gotten around to reviewing it. So the environment does not seem to work right now. So I made some local changes. If you give me the rights to push to your branch I can push those changes. However, I have not been able to fix all problems (for example, I am currently stuck at converting the action to a coordinate).

**Comment by everthemore** [comment]
Great! Thanks for going through that effort, I can take over from there for a next round of fixes. I'll make sure to test it locally to see if it runs correctly. Updating the rights for you to push in a bit, thanks!

**Comment by everthemore** [comment]
This should now be compatible with SciGym!

**Review by HendrikPN — APPROVED** [review]

**Pull request merged**
